### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by swissonid** [long1eu/flutter_i18n#1]
When I try to use the plugin I got that error....do I make something wrong or is it the plugin?? 

`I/flutter (30012): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (30012): The following NoSuchMethodError was thrown building MyApp(dirty):
I/flutter (30012): The getter '_locale' was called on null.
I/flutter (30012): Receiver: null
I/flutter (30012): Tried calling: _locale
I/flutter (30012): 
I/flutter (30012): When the exception was thrown, this was the stack:
I/flutter (30012): #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
I/flutter (30012): #1      S.of (package:bill_scanner/generated/i18n.dart:20:25)`

`class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      localizationsDelegates: [S.delegate],
      supportedLocales: S.delegate.supportedLocales,
      localeResolutionCallback: S.delegate.resolution(fallback: new Locale("en", "")),
      theme: new ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or press Run > Flutter Hot Reload in IntelliJ). Notice that the
        // counter didn't reset back to zero; the application is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: "test title"),
    );
  }
}`

` floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: S.of(context).title,
        child: new Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.`

**Comment by long1eu** [comment]
Did you initialized the App with:
```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      localizationsDelegates: [S.delegate],
      supportedLocales: S.delegate.supportedLocales,
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
```

**Comment by long1eu** [comment]
Try to hit the _Build String Resources_ button  and try again.

**Comment by swissonid** [comment]
The "App" has right now only two files, [here you can see it](https://gist.github.com/swissonid/7ce5a7df0b5cd7df2cf6a0fff3a9ed02). I rebuild the whole project and the resource, just to get sure 😄

**Comment by long1eu** [comment]
Hi! so i copy the exact code but I don't get the error.

**Comment by long1eu** [comment]
Please reopen if you still have any questions.

**Comment by andretietz** [comment]
I do have the same problem. Don't know how to solve it.

How I can reproduce it all the time:

* Create a new flutter project using Android Studio 3.0.1 with the flutter plugin and this one.

* Update the Demo as described in the docs:
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      localizationsDelegates: [S.delegate],
      supportedLocales: S.delegate.supportedLocales,
      localeResolutionCallback: S.delegate.resolution(fallback: new Locale("en", "")),
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
```
* Make some use of the library:
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      localizationsDelegates: [S.delegate],
      supportedLocales: S.delegate.supportedLocales,
      localeResolutionCallback: S.delegate.resolution(fallback: new Locale("en", "")),
      title: S.of(context).appTitle,
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: S.of(context).appTitle),
    );
  }
}
```
Result:

![error](https://user-images.githubusercontent.com/2174386/34639955-ed57ce80-f2e9-11e7-9b9e-273d50062781.PNG)


I tried:
* Adding the internationalization plugin as described [here](https://flutter.io/tutorials/internationalization/), but I guess the plugin does this already.
* Adding the *.arb files as resouces in the pubspec.yaml:
```yaml
  # To add assets to your application, add an assets section, like this:
  assets:
    - res/values/strings_en.arb
```

Nothing did work so far

**Comment by long1eu** [comment]
Perfect, I'll take a look. Thanks

Pe 6 ian. 2018 15:06, "André Tietz" <notifications@github.com> a scris:

**Comment by long1eu** [comment]
This is still on. I will inform you when it's fixed.

**Comment by andretietz** [comment]
Cool, thanks

**Comment by long1eu** [comment]
I've managed to fix the bug. Waiting on Intellij approval for the update.
[flutter_i18n.zip](https://github.com/long1eu/flutter_i18n/files/1633915/flutter_i18n.zip)

**Comment by biklas7** [comment]
I'm having the exact same problem on version 0.0.4 of the plugin.

It's in this line -> `s._lang = getLang(s._locale);`

> The following NoSuchMethodError was thrown building PageEntry(dirty, state: _StateEntry#bfd13):
Class 'en' has no instance getter '_locale'.
Receiver: Instance of 'en'
Tried calling: _locale

If I add the getter for locale like this `Locale get locale => _locale;` that error doesn't happen but another one pops up:

> The following NoSuchMethodError was thrown building PageEntry(dirty, state: _StateEntry#0327b):
Class 'en' has no instance setter '_lang'.
Receiver: Instance of 'en'
Tried calling: _lang"en"

If I add the setter like this `set lang(value) => _lang = value;` this error won't happen but again another one pops up.

> The following assertion was thrown building PageEntry(dirty, state: _StateEntry#f595f):
type 'en' is not a subtype of type 'S' of 'function result' where
en is from package:my_app/generated//i18n.dart
 S is from package:my_app/generated/i18n.dart

For this one I have no idea how to solve, I can see that it says that the path is wrong (`generated//i18n.dart`) but I don't know what to do.

@long1eu please take a look at this. Thanks

**Comment by vjrj** [comment]
I get this issue but using in `MaterialApp` of:
 
```
 onGenerateTitle: (context) => S.of(context).appName,
```

instead of 
```
 title: S.of(context).appName,
```

fixed for me.
