### ISSUE TITLE
Cannot escape dollar($) sign

### ISSUE THREAD

**Issue by arlindiDev** [long1eu/flutter_i18n#11]
In the .arb file I added a string:
 `"test": "In my wallet I have \$10",`
In the i18n.dart file that gets generated to:
 `String test(String 10) => "In my wallet I have \$10";`
So it creates a parameter for the $ dollar sign but I actually want the $ sign to be part of my String. It is not escaping it.

**Comment by long1eu** [comment]
Good issue. I'll fix it.

**Comment by noordawod** [comment]
Is this fixed @long1eu?

**Comment by long1eu** [comment]
not yet, let me do it

**Comment by long1eu** [comment]
done, should be fixed by my last commit
