### ISSUE TITLE
How to handle nest data?

### ISSUE THREAD

**Issue by jintangWang** [long1eu/flutter_i18n#111]
I knew `.arb` don't support nest data, like this：
``` json
{
  "common": {
      "day": "day",
      "yes": "Yes",
      "no": "No",
   }
}
```
Do you have any smart suggestions? Because it tortures me if I change data to below:
``` json
{
  "common_day": "day",
  "common_yes": "yes",
  "common_no": "no"
}
```

**Comment by noordawod** [comment]
Well, from my experience with software design and architecture, keep it simple :) if you impose a certain structure on your data model (in this case it's linguistic data), then your tools, code, and any 3rd party software you may want to use will need to be able to read this structure. I'm not sure this is the right way to go.

For example, I don't know if any of the online translation tools support nesting.

**Comment by jintangWang** [comment]
Thanks. It's a clever option. I found a [jsfiddle](http://fiddle.jshell.net/blowsie/S2hsS/show/light/) almost match my require. So I forked and modified a little to use in `.arb`. Here is it. http://jsfiddle.net/jintang/bmgvw48n/7/  Thanks again.
