### ISSUE TITLE
Google Translator Toolkit shutting down

### ISSUE THREAD

**Issue by rickcasson** [long1eu/flutter_i18n#124]
First of all, thank you for creating an awesome plugin to simplify localization within Flutter! It has been really useful to us so far!

[With Google shutting down its Translator Toolkit after December 4th, 2019](https://support.google.com/translatortoolkit/answer/9462068), I'm wondering what your plan is for this plugin? Will you start directing people to use an alternative (paid) translation tool that supports ARBs such as [Crowdin](https://crowdin.com/), or will you modify the plugin to use an alternative file format supported by [other translation tools](https://en.wikipedia.org/wiki/Comparison_of_computer-assisted_translation_tools)? Are there any other i18n tools that anyone can recommend?

We're quickly trying to wrap up some of our translation projects before Translator Toolkit shuts down, but are hoping to sort out an alternative path forward before too long.

**Comment by marcruse** [comment]
You can use [Localizely](http://localizely.com/). 
They support ARB files, pretty easy to use.
