### ISSUE TITLE
Key based get

### ISSUE THREAD

**Issue by juliocbcotta** [long1eu/flutter_i18n#13]
Hi, would it be possible to have something like  `S.get(key)` ? I would like to associate a list of settings keys with displayable strings.
Today I have to have a switch for each key, which it not very developer friendly.

**Comment by long1eu** [comment]
hi!

Can you explain this a little more, maybe providing an example?

**Comment by juliocbcotta** [comment]
I have an enum class that I use to save some settings in my shared preferences.
Today I have to write a switch/case when I need to associate each enum value with a localised string.
It would be great if it was possible to pass the enum instance string and get an associated localised string.

Maybe some reflection based `get` method would do. I would pass the enum instance name and the lib return the localised string.

**Comment by long1eu** [comment]
Not quite possible since Flutter doesn't support mirrors(reflection) ATM. Thanks for the suggestion.
