### ISSUE TITLE
Flutter i18n plugin not working with intellij 2019.3 

### ISSUE THREAD

**Issue by DhavalRKansara** [long1eu/flutter_i18n#130]
After upgrading my Intellij to the latest version 2019.3, [flutter i18n](https://plugins.jetbrains.com/plugin/10128-flutter-i18n/) plugin is not working properly. Even when I am trying to import [flutter i18n](https://plugins.jetbrains.com/plugin/10128-flutter-i18n/) from disk it gives me the below error:

<img width="400" alt="Screen Shot 2019-12-19 at 1 16 29 PM" src="https://user-images.githubusercontent.com/44993081/71154561-c9246880-2261-11ea-814a-697262d72fa7.png">

Also, after installing the plugin from Marketplace, `i18n.dart` file is not auto-generating in my project.

It was working fine till the flutter version 2019.2.

**Comment by avimak** [comment]
pls see here - https://github.com/long1eu/flutter_i18n/issues/125

**Comment by DhavalRKansara** [comment]
> pls see here - #125

Okay, #125 is the same as this one so I am closing this issue here.
