### ISSUE TITLE
Support for resource attributes

### ISSUE THREAD

**Issue by NMateu** [long1eu/flutter_i18n#14]
Hi, 

it would be great if it was possible to properly parse files with nested JSON like is described here https://github.com/googlei18n/app-resource-bundle/wiki/ApplicationResourceBundleSpecification#resource-attributes

**Comment by long1eu** [comment]
Sure. What would be a use case that you see?

**Comment by NMateu** [comment]
Hi @long1eu 

the simplest sample will be something like this:

> "TUTORIAL": {
    "TUT_ONE": {
      "TITLE": "title 1",
      "DESC": "desc 2"
    },
    "TUT_TWO": {
      "TITLE": "title 2",
      "DESC": "desc 2"
    },
    "TUT_THREE": {
      "TITLE": "title 3",
      "DESC": "desc 3"
    },
    ...
  },

**Comment by long1eu** [comment]
Not sure you understood the attributes right. Those attributes are for just one attributes and not for nested resources. Not planning to add that anytime soon since it's out of arb scope. Let me know if you feel that I'm wrong.
