### ISSUE TITLE
How to change language promatically

### ISSUE THREAD

**Issue by falll2000** [long1eu/flutter_i18n#15]
I use this plug-in can change language when app start-up.

But if I want to change language programmatically, who to do so.

ex: change language when I click a button.  

thanks a lot :)

**Comment by NMateu** [comment]
hi, 
this should help you https://gist.github.com/ilikerobots/474b414138f3f99150dbb3d0cc4cc721

**Comment by long1eu** [comment]
Thanks @NMateu

**Comment by etet2007** [comment]
But it seems that you have to change the state of MaterialApp, and this will reload the entire app. Is there any ways to change language in a setting page but not reload the app? Thanks!

**Comment by long1eu** [comment]
I don't see the problem rebuilding the MaterialApp widget.

**Comment by etet2007** [comment]
> I don't see the problem rebuilding the MaterialApp widget.

It's usable but other widgets will lose their states. I think it's best to stay in the same page after you change language.
https://github.com/flutterchina/gitme
This app is an example.

**Comment by long1eu** [comment]
No they won't lose their state. They will be rebuilt with the new Localization parent. Can you provide a MWE ? Maybe I don't get it right.

**Comment by etet2007** [comment]
Forgive my poor expression ability.
What I have done:
![localization](https://user-images.githubusercontent.com/12908406/51011794-e2725e80-1594-11e9-87fc-6f7d07c4256f.gif)
What I want:
![qq20190111-0](https://user-images.githubusercontent.com/12908406/51011973-c3280100-1595-11e9-93f3-5498c68c543d.gif)

**Comment by etet2007** [comment]
> No they won't lose their state. They will be rebuilt with the new Localization parent. Can you provide a MWE ? Maybe I don't get it right.

You are right. It's my mistake. There is another problem to make my app reload.

What's more. I find that we can change locale field in MaterialApp to "change language promatically ".
```
class _AppState extends State<App> {

  var locale;
  changeLocale(Locale locale) {
    setState(() {
      this.locale = locale;
    });
  }

  @override
  Widget build(BuildContext context) {
    return LocaleWidget(
      child: MaterialApp(
        title: UIData.appName,
        locale: locale,     // THIS
        home: MainPage(),
        localizationsDelegates: [
          S.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],
        supportedLocales: S.delegate.supportedLocales,
      ),
      changeLocale: changeLocale,
    );
  }

```

Your plugin is so great. I am deeply grateful for you help.
