### ISSUE TITLE
How can I add text after a parameter?

### ISSUE THREAD

**Issue by talmor-guy** [long1eu/flutter_i18n#16]
I am looking to add a string like "Weight: 20Kg" where 20 should be parameterised and followed by "Kg" without a separating space, however writing something like "Weight: $weightKg" ends up with a variable called weightKg and "Weight: ${weight}Kg" results in a function with bas syntax (missing argument name). Is there a way to overcome this?

**Comment by long1eu** [comment]
try `"Weight: ${weight}\Kg"`

**Comment by talmor-guy** [comment]
Not working, it still results with a no argument function.

**Comment by noordawod** [comment]
I also didn't manage to find a way to accomplish this. If I get some free time this week, I can check and submit a PR.

**Comment by long1eu** [comment]
So it looks like it work like this
```
{
    "weight": "the weight is $weight\Kg",
}
```

The resulting code is   
```String weight(String weight) => "the weight is $weight\Kg";```

Is this what you expected?

**Comment by noordawod** [comment]
Actually, I think this is a bad hack and the proper way to do it is like this:

```
String weight(String weight) => "the weight is ${weight}Kg";
```

But currently the plugin doesn't properly handle `{`  `}` or even `\{` `\}`, which I believe it should.

How hard can it be to patch the plugin? I don't think it would take that much time to support curly parentheses...

**Comment by long1eu** [comment]
Sorry but I don't see a reason to support {}. Using "${variable} and
another text" is against Dart styles code. You should only use {} when you
reference something from that variable.

https://www.dartlang.org/guides/language/effective-dart/usage#avoid-using-curly-braces-in-interpolation-when-not-needed

Let me know your thoughts on this.

Also if you don't think it would take much time to add support for the
'feature' you are requesting your pull request will be highly appreciated.

**Comment by noordawod** [comment]
Definitely agree with Dart styles code, but I just mean that if Dart supports { }, the plugin should at least offer support for it. That's all :)

I think I will do that, no problem.

**Comment by long1eu** [comment]
Thank you so much!

On Nov 19, 2018 15:12, "Noor Dawod" <notifications@github.com> wrote:

Definitely agree with Dart styles code, but I just mean that if Dart
supports { }, the plugin should at least offer support for it. That's all :)

I think I will do that, no problem.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/long1eu/flutter_i18n/issues/16#issuecomment-439887827>,
or mute the thread

**Comment by noordawod** [comment]
Added support in pr #27
(sorry for the delay, I've been busy)

**Comment by noordawod** [comment]
@long1eu this can be closed after pr merge I believe.
