### ISSUE TITLE
Support newer versions of IntelliJ/Android Studio

### ISSUE THREAD

**Issue by g123k** [long1eu/flutter_i18n#22]
Hello, 

The plugin is currently supporting a 181.x version of IntelliJ.
The current stable version of IntelliJ is 182.x and some RC for 183.x are even available.

Do you plan to support these new releases?

Thanks for your work!

**Comment by noordawod** [comment]
https://plugins.jetbrains.com/plugin/10128-flutter-i18n

It's there.

**Comment by noordawod** [comment]
@long1eu this can be closed now I believe.
