### ISSUE TITLE
LocaleListResolutionCallback is not a class.

### ISSUE THREAD

**Issue by jeroentrappers** [long1eu/flutter_i18n#23]
After updating to version 0.1.1 in Android Studio, this class (or rather function definition) is not found.

**Comment by smiLLe** [comment]
same for me. @jeroentrappers did you find an easy fix?

**Comment by noordawod** [comment]
Update your Flutter code, this is a new class in Flutter dev (and maybe beta) branch.

**Comment by noordawod** [comment]
@long1eu this can be closed now I believe.
