### ISSUE TITLE
supporting language with multiple script code for iOS

### ISSUE THREAD

**Issue by kaiyan910** [long1eu/flutter_i18n#24]
Currently iOS cannot display the correct language when the target language contains more than 1 script code (e.g. chinese with tranditional chinese (zh_hant) and simplified chinese (zh_hans)).

and seems this issue provided the solution:
https://github.com/flutter/flutter/issues/22642

any plan on fixing this ? thanks

**Comment by noordawod** [comment]
@kaiyan910 maybe you want to submit a pr to address this use case?

**Comment by long1eu** [comment]
I tried to add an `strings_zh_hant_HK.arb` file and the corresponding class get's generated. So as long as you specify it correctly in supportedLocales like this:

```dart
// Full Chinese support for CN, TW, and HK
supportedLocales: [
  const Locale.fromSubtags(languageCode: 'zh'), // generic Chinese
  const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hans'), // generic simplified Chinese
  const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant'), // generic traditional Chinese
  const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hans', countryCode: 'CN'),
  const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant', countryCode: 'TW'),
  const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant', countryCode: 'HK'),
]
```

it should not be an issue.
Let me know if this works for your.
