### ISSUE TITLE
Can't resolve string value resource

### ISSUE THREAD

**Issue by baoxiehao** [long1eu/flutter_i18n#28]
This plugin of Flutter is awesome! But I have encountered the issue that when I have added more string to the arb files, the i18n.dart is not re-generated automatically. How can I trigger it manually?

I'm using Android Studio 3.2

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.11.12, on Mac OS X 10.14.1 18B75, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] Android Studio (version 3.0)

**Comment by miduch** [comment]
having same issue

**Comment by noordawod** [comment]
It should work once every minute, that's how the plugin is programmed even though my Android Studio regenerates the `i18n.dart` instantly. Try uninstalling and reinstalling maybe?

**Comment by long1eu** [comment]
![screen shot 2018-12-14 at 13 21 07](https://user-images.githubusercontent.com/9283414/50000743-27f63880-ffa3-11e8-9b07-9272f46ce321.png)
Next to the run button you should have the generate arb icon. Closing this as duplicate

**Comment by noordawod** [comment]
Thanks, I never saw that :)

**Comment by baoxiehao** [comment]
Thanks. I've never met the problem again.

By the way, any plan to support the string array?
