### ISSUE TITLE
Plugin cannot deal with Chinese Quotation Marks(“”) and Angle Quotation Mark(《》) correctly

### ISSUE THREAD

**Issue by UkonnRa** [long1eu/flutter_i18n#31]
When writing a Chinese sentence: `这本书《$bookName》很棒`, the plugin will recognize `《》` as a part of the param also, so does `“”`

**Comment by long1eu** [comment]
Perfect finding. Can you try the new version of the plugin? https://github.com/long1eu/flutter_i18n/releases/tag/v0.2 
With the new version you would be able to wrap the param into parenthesis. So your string would be
`这本书《${bookName}》很棒`

This should work.

**Comment by UkonnRa** [comment]
It works! Good job! Hope you can push it to IntelliJ's plugin market. Cannot wait to update!

**Comment by long1eu** [comment]
fixed in version 0.2, waiting for publish
