### ISSUE TITLE
The getter '{string_key}' was called on null.

### ISSUE THREAD

**Issue by ammar-esrawi** [long1eu/flutter_i18n#35]
`static S of(BuildContext context) => Localizations.of<S>(context, S);  ,`
 this call returns null 
so the usage like will produce the exception **The getter '{string_key}' was called on null.**

**Comment by long1eu** [comment]
I need more info.

**Comment by ammar-esrawi** [comment]
@long1eu 
I think the problem comes from the flutter frame work it self 
but in general the issue occur once you try to reach the S.of(context).SOMETHING inside a StateFull widget this will make the call` return Localizations.of<S>(context, S);` returns null instead of instance from S class 

,i created another issue in the flutter repo it contains more details 
please follow [this](https://github.com/flutter/flutter/issues/26365)

i am using this SDK 
```
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
```

**Comment by long1eu** [comment]
You didn't setup the plugin. You don't have the proper LocalisationDelegate
into you app. Follow the instructions carefully.

În joi, 10 ian. 2019, 19:35 ammar-esrawi <notifications@github.com a scris:

**Comment by long1eu** [comment]
Feel free to reopen the issues if you have the same problem after following the instructions.

**Comment by ammar-esrawi** [comment]
i tested your sample app and it did not work for me 
in your app you setup the delegates and supported locals but did not call the values, i cloned your app and only changed one line in the main.dart file 

`home: MyHomePage(title: S.of(context).app_name),`

```

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      onGenerateTitle: (BuildContext context) => S.of(context).app_name,
      localizationsDelegates: const <LocalizationsDelegate<WidgetsLocalizations>>[
        S.delegate,
      ],
      supportedLocales: S.delegate.supportedLocales,
      localeResolutionCallback:
          S.delegate.resolution(fallback: const Locale('en', '')),
      localeListResolutionCallback:
          S.delegate.listResolution(fallback: const Locale('en', '')),
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: S.of(context).app_name),
    );
  }
}

```

this generated the following log

```
Initializing hot reload...
Syncing files to device Android SDK built for x86...
I/flutter ( 3688): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 3688): The following NoSuchMethodError was thrown building MyApp(dirty):
I/flutter ( 3688): The getter 'app_name' was called on null.
I/flutter ( 3688): Receiver: null
I/flutter ( 3688): Tried calling: app_name
I/flutter ( 3688): 
I/flutter ( 3688): When the exception was thrown, this was the stack:
I/flutter ( 3688): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter ( 3688): #1      MyApp.build (package:test_app/main.dart:23:45)
I/flutter ( 3688): #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3774:28)
I/flutter ( 3688): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter ( 3688): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 3688): #5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter ( 3688): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter ( 3688): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 3688): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 3688): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 3688): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 3688): #12     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 3688): #13     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 3688): #14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 3688): (elided one frame from package dart:async)
I/flutter ( 3688): ════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 420 libraries in 1,341ms.
 

```

note : 
i can not reopen the issue 

### Thank you for the very useful plugin

**Comment by ammar-esrawi** [comment]
dart versaion
![image](https://user-images.githubusercontent.com/40269203/50993504-83740180-1522-11e9-878e-5bc515c6cd6e.png)

flutter version
![image](https://user-images.githubusercontent.com/40269203/50993553-a6061a80-1522-11e9-8b3f-f6d228b72b51.png)

**Comment by long1eu** [comment]
Your you can't use S with that context. S.of(context) will always return null.

**Comment by long1eu** [comment]
try it like this
```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      onGenerateTitle: (BuildContext context) => S.of(context).app_name,
      localizationsDelegates: const <LocalizationsDelegate<WidgetsLocalizations>>[
        S.delegate,
      ],
      supportedLocales: S.delegate.supportedLocales,
      localeResolutionCallback: S.delegate.resolution(fallback: const Locale('en', '')),
      localeListResolutionCallback: S.delegate.listResolution(fallback: const Locale('en', '')),
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Builder(
        builder: (BuildContext context) {
          return MyHomePage(title: S.of(context).app_name);
        },
      ),
    );
  }
}
```

**Comment by ammar-esrawi** [comment]
> try it like this
> 
> ```
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       onGenerateTitle: (BuildContext context) => S.of(context).app_name,
>       localizationsDelegates: const <LocalizationsDelegate<WidgetsLocalizations>>[
>         S.delegate,
>       ],
>       supportedLocales: S.delegate.supportedLocales,
>       localeResolutionCallback: S.delegate.resolution(fallback: const Locale('en', '')),
>       localeListResolutionCallback: S.delegate.listResolution(fallback: const Locale('en', '')),
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: Builder(
>         builder: (BuildContext context) {
>           return MyHomePage(title: S.of(context).app_name);
>         },
>       ),
>     );
>   }
> }
> ```


this worked fine thank you

**Comment by long1eu** [comment]
Do you understand why?

În mar., 15 ian. 2019, 00:04 ammar-esrawi <notifications@github.com a scris:

**Comment by ammar-esrawi** [comment]
Yep i have been using the widget context since your generated Class S deppend on Localizations which only work in Material context so it worked through the builder 

I think these information need to be documented in Flutter website cuz i read the documents but this important info were not presented 

I appreciate your efforts 

Also i wish if you can work on a plugin for the toJson ,fromJson also, they are annoying issue

**Comment by long1eu** [comment]
try https://pub.dartlang.org/packages/built_value

**Comment by po1arbear** [comment]
delete the 'generated' package, then it will recreate automatic ,solved my problem

**Comment by ahmedGibran** [comment]
Isolate the user interface from the main application and it will work for you.
<img width="593" alt="‏لقطة الشاشة 2021-02-17 في 12 18 41 ص" src="https://user-images.githubusercontent.com/51888694/108128829-067ac500-70b6-11eb-8181-0c5464a29223.png">
