### ISSUE TITLE
how to localize for chinese

### ISSUE THREAD

**Issue by AkoWu101** [long1eu/flutter_i18n#38]
i try to define 
string_zh.arb => Traditional Chinese for Taiwan
string_zh_CN.arb => Simplify Chinese
string_zh_HK.arb => Traditional Chinese for Hong Kong

but, always use string_zh_HK when switching different chinese language.

What is the correct way to handle it?

**Comment by noordawod** [comment]
Need more details:

- What IDE are you using? what version?
- Version of the i18n plugin you're using.
- Snippet of code that you're using.

Thanks.

**Comment by noordawod** [comment]
Reopen if still a problem.
