### ISSUE TITLE
Does not support to generate locale's scriptCode with country code

### ISSUE THREAD

**Issue by AkoWu101** [long1eu/flutter_i18n#39]
I create strings_zh_Hant_HK and strings_zh_Hans_CN. 
supportedLocales cannot generate Locale with scriptCode and country code

**Comment by noordawod** [comment]
Is this still an issue @KingWu?

If so, please provide:

- Output of `flutter doctor -v`
- IDE version (screenshot of Help > About is best)
- Plugin version

Thanks.

**Comment by noordawod** [comment]
Duplicate of #73
