### ISSUE TITLE
variables ended with "...One" and "...Two" did not generate

### ISSUE THREAD

**Issue by yuzurihaaa** [long1eu/flutter_i18n#41]
`strings_en.arb`
```
{
  "variableOne" : "value one",
  "variableTwo" : "value two",
  "variableThree" : "value three"
}
```

Only `variableThree` is generated but `variableOne` and `variableTwo` are not. Is it related to `.arb` file?

**Comment by long1eu** [comment]
You need to also have a value `Other`.

**Comment by long1eu** [comment]
```
{
  "variableOne" : "value one",
  "variableTwo" : "value two",
  "variableThree" : "value three",
  "variableOther" : "value other"
}
```

**Comment by yuzurihaaa** [comment]
ahh I see, it does
```
String variable(dynamic param) {
    switch (param.toString()) {
      case "1":
        return "value one";
      case "2":
        return "value two";
      default:
        return "value other";
    }
  }
```
Tbh, I thought it'll generate `String get variableThree => "value three";`
Where can I get information related to this? I tried to find info about this in [here](https://github.com/googlei18n/app-resource-bundle/wiki/ApplicationResourceBundleSpecification#resource-id), but can't find the right info.

**Comment by long1eu** [comment]
Here
https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/lib/src/l10n/README.md
