### ISSUE TITLE
Is there a plugin config option?

### ISSUE THREAD

**Issue by surpher** [long1eu/flutter_i18n#48]
Great plugin, and thanks for sharing it!

But I do think that generating a class named `S` can be a bit confusing when reading through the code after a few weeks/months.

Is there a way to override/set/change the name of the auto-generated class?

For example, I would change the config of the plugin to generate a class called `Strings` and use it as `Strings.of(context).myStringKey` or maybe `IntlStrings`. That way when I (or someone else going through the codebase) can avoid asking themselves what `S` is.

**Note:** I have created a wrapper around S:
```
class Strings extends S {
  static Strings of(BuildContext context) => S.of(context);
}
```
Works fine when running the app with context and all. 
But am now hitting problems when running unit tests. They're failing with:
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞══════════════════
The following assertion was thrown building BlocBuilder<IssueEvent, IssueState>(dirty, dependencies:
[_LocalizationsScope-[GlobalKey#176cc]], state: _BlocBuilderBaseState<IssueEvent,
IssueState>#4fc5b):
type '$en' is not a subtype of type 'Strings'
...
```
Because `$en` is a subclass of `S` in the auto-generated file just as Strings is, and now Strings and $en are siblings. 

Cheers.

**Comment by noordawod** [comment]
With #98 there's initial support for configuring the plugin through pubspec. So keeping this here for a later implementation.
