### ISSUE TITLE
feature: custom boiler-plate code templates

### ISSUE THREAD

**Issue by ayushin** [long1eu/flutter_i18n#49]
Hey, great plugin!

It would be helpful though to allow customer boiler plate code templates. In particular I would like to do something like:

```
class S implements WidgetsLocalizations {

  static S current;
```

and have the GeneratedLocalizationsDelegate do something like:

```
  @override
  Future<S> load(Locale locale) {
    final String lang = getLang(locale);
    if (lang != null) {
      switch (lang) {
        case "cs":
          S.current = const $cs();
          return SynchronousFuture<S>(S.current);

```
so that I can also use the internationalised strings outside of the build context, e.g. in blocs.

Any chance?

**Comment by ayushin** [comment]
Or perhaps this is worth including in the standard boiler plate code? so you can also use S.current.your_string throughout your code

**Comment by ayushin** [comment]
I've created a pull request https://github.com/long1eu/flutter_i18n/pull/50 if anyone is interested.

**Comment by noordawod** [comment]
Thanks @ayushin for your contribution! I have added a couple of comments regarding your pr, just fix those and it's good to merge.

**Comment by ayushin** [comment]
@noordawod for some reason it wouldn't build with my IDE, i won't have time right now to investigate, but feel free to modify my contribution in any way you like if this helps somebody in the meantime
