### ISSUE TITLE
Constructor of he_IL class generated with const

### ISSUE THREAD

**Issue by sleonidy** [long1eu/flutter_i18n#5]
And it is breaking 
```dart
Future<WidgetsLocalizations> load(Locale locale)
```
where it called with const

**Comment by long1eu** [comment]
[flutter_i18n.zip](https://github.com/long1eu/flutter_i18n/files/2047273/flutter_i18n.zip)
Thanks for pointing this out. I made the fix. You can use this version until is available in Intellij

**Comment by sleonidy** [comment]
Thanks for the quick resolution

**Comment by long1eu** [comment]
You're very welcome. Does it work for you?

**Comment by sleonidy** [comment]
Yep.
You can close the issue.
Thanks again
