### ISSUE TITLE
generated/i18n.dart have no generate

### ISSUE THREAD

**Issue by MagicalWater** [long1eu/flutter_i18n#52]
i installed plugin and setting arb file already, but generated/i18n.dart have no generate.

**Comment by kishan2612** [comment]
Add this as misc.xml in .Idea
`<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="ExternalStorageConfigurationManager" enabled="true" />
  <component name="NodePackageJsonFileManager">
    <packageJsonPaths />
  </component>
  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_8" project-jdk-name="1.8" project-jdk-type="JavaSDK">
    <output url="file://$PROJECT_DIR$/out" />
  </component>
</project>`

**Comment by MagicalWater** [comment]
> Add this as misc.xml in .Idea
> `<?xml version="1.0" encoding="UTF-8"?> <project version="4"> <component name="ExternalStorageConfigurationManager" enabled="true" /> <component name="NodePackageJsonFileManager"> <packageJsonPaths /> </component> <component name="ProjectRootManager" version="2" languageLevel="JDK_1_8" project-jdk-name="1.8" project-jdk-type="JavaSDK"> <output url="file://$PROJECT_DIR$/out" /> </component> </project>`

this worked, thank you~.

**Comment by noordawod** [comment]
Great, thanks @kishan2612 for your help!
