### ISSUE TITLE
IntelliJ 2019.1

### ISSUE THREAD

**Issue by noordawod** [long1eu/flutter_i18n#53]
There's a new kid on the block and this plugin needs to be upgraded to support it. At least I still don't see the plugin in its latest version in JetBrains.

**Comment by zaralockheart** [comment]
hmmm.. seems like it doesn't work for exist project, but it works for new project :/

**Comment by Lootwig** [comment]
https://plugins.jetbrains.com/plugin/10128-flutter-i18n/versions

For some reason, 0.0.6+1 is the last one marked upward compatible beyond 2018.3.6. Is there no way to specify newer releases as "unbounded" upward compatible as well?

**Comment by umutseven92** [comment]
Any update on this? The 0.06 version that is available for 2019.1 is very old.

**Comment by noordawod** [comment]
This will be fixed once #98 is merged.

**Comment by noordawod** [comment]
Also, latest plugins are now on JetBrains.
