### ISSUE TITLE
Will this support dynamic string getter?

### ISSUE THREAD

**Issue by 100cm** [long1eu/flutter_i18n#58]
If i store a i18n key in variables like this:
`var key = "username"`

and i want to translate it by this plugin , How can i do this?

I know the simplest way is `S.of(Context).username`

But Is there any solution that i can call `S.of(Context).byKey(key)` ?

**Comment by noordawod** [comment]
The library allows you to embed variables in the JSON, like so:

```json
{
  "helloWorld": "Hello, $name",
}
```

Then in code:

```dart

  final name = 'John Doe';

  S.of(context).helloWorld(name);

```

Is that what you want?

**Comment by 100cm** [comment]
@noordawod  No, I know how to use dynamic variable in value string, I just want to call the getter dynamically, for example

if My api server returns some entity's status
```
{
 status: "VALID || INVALID" 
}

```
and i want to translate the status by the response value.

 i must call `S.of(context).valid` or  `S.of(context).invalid` to translate it. So If i could call it by response value like `S.of(context).getValue(response.status)` , this will be more convenient

**Comment by 100cm** [comment]
If the generator could generate a map(save the arb translation data) , i think it could be done .(just because flutter doesn't support reflection :( )

**Comment by 100cm** [comment]
hello there?

**Comment by noordawod** [comment]
@100cm nah, this is a strictly static-only localization library, and what you're describing is a business logic of the app. I recommend you use a state variable to accomplish that.
