### ISSUE TITLE
how to use this in VSCode editor

### ISSUE THREAD

**Issue by phpmaple** [long1eu/flutter_i18n#61]
I use editor from Android Studio to VSCode, and how to use this in VSCode editor?

**Comment by noordawod** [comment]
This plugin is written in Java and is incompatible with VS Code.

**Comment by mrkpatchaa** [comment]
As you declared working on the VSCode extension, where can we find it and test ? 
Thanks.
I've found this, https://marketplace.visualstudio.com/items?itemName=esskar.vscode-flutter-i18n-json , but they're using json. The approach is very similar.

**Comment by noordawod** [comment]
@long1eu ?
