### ISSUE TITLE
Change Language at run time from other Screen

### ISSUE THREAD

**Issue by Purus** [long1eu/flutter_i18n#65]
My question is similar to https://github.com/long1eu/flutter_i18n/issues/15. But have an issue understanding it as it's not similar to the class generated by the plugin.

The gist shows changing the language from the Main/Home screen. In my I have a settings screen and user can change their language. When a language is selected, the new language should be reflected.

I am using the below code in my Settings page, when the user changes the language. But it does not have any effect.

> S.delegate.load(new Locale(value));

what I am doing wrong? What is the right approach? Thanks in advance.

**Comment by Purus** [comment]
This is my main app code. Any help would be useful.

```
runApp(
    DesignsBlocProvider(
      child: AuthBlocProvider(
        child: UserBlocProvider(
          child: MaterialApp(
            onGenerateTitle: (BuildContext context) => S.of(context).app_title_name,
            theme: ThemeData(
              primarySwatch: Colors.pink,
            ),
            home: BlouseDesignApp(),
            localizationsDelegates: [
              S.delegate,
              GlobalMaterialLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate
            ],
            supportedLocales: S.delegate.supportedLocales,
            localeResolutionCallback:
            S.delegate.resolution(fallback: const Locale('en', '')),
          ),
        ),
      ),
    ),
  );
```

**Comment by mis0025033** [comment]
Same problem. Anyone can help? Thanks

**Comment by Purus** [comment]
I am holding my app release just for this issue. If someone can help it
would be of great help. Thanks in advance.

Thanks,

Purusothaman Ramanujam

**Comment by mis0025033** [comment]
Refer to [https://medium.com/saugo360/managing-locale-in-flutter-7693a9d4d6ac](url)
Section: Allowing the user to change the locale
I can now switch to different language in app setting page for whole app .
Work in both Android and ios.
Hope this example can help you.

**Comment by Purus** [comment]
I have seen this before. But isn't different than what this plugin
generates as a code?

Your are using this plugin? Thanks for your time.

Thanks,

Purusothaman Ramanujam

**Comment by mis0025033** [comment]
I am using flutter_i18n plugin, but when i use load function, it can't update the locale for the app.
So, I think S.delegate may not work well or there is some kind of information hasn't been mentioned in the document.

So, I try to find out is there any other approach can only update the locale for whole app from any page, and i found this example. And just implement this for updating locale and the rest i am still using flutter_i18n

```
static void setLocale(BuildContext context, Locale newLocale){ 
  _MyAppState state = context.ancestorStateOfType(TypeMatcher<_MyAppState>());
  state.setState(() {
    state.locale = newLocale;
  });
}
```

I don't think this is a very good solution, but it can solve my problem at this moment, and i hope flutter_i18n can provide a detail document to explain how to implement updating locale by user

**Comment by Purus** [comment]
Wow. Thanks a lot. You saved my day. Thanks again for your help.

I am sure this should be somewhere documented in the wiki.

Thanks,
R.Purusothaman

**Comment by Purus** [comment]
Please confirm on the best approach. I am not sure if this is the only
approach which is best.

Thanks,

Purusothaman Ramanujam

**Comment by noordawod** [comment]
This is beyond the scope of this plugin, @Purus, maybe you can check StackOverflow instead?

**Comment by mrkpatchaa** [comment]
I think it is in the scope of this plugin because the i18n file is generated by the plugin. 
I've created a pull request to address this issue. 
Check #97 .
