### ISSUE TITLE
Plugin should not run on dart project without flutter

### ISSUE THREAD

**Issue by hacker-cb** [long1eu/flutter_i18n#68]
I have dart plain project (without flutter) and flutter_i18n creates `lib/generated` and `res\values\strings_en.arb` files in it. 
How to disable such behavior?

I think it will be better if plugin will work **ONLY** if there is dependency to flutter in the `pubsec.yaml`

**Comment by noordawod** [comment]
Related to #67

**Comment by noordawod** [comment]
This will be fixed once #98 is merged.

**Comment by noordawod** [comment]
This is now resolved in v1.1.0. Please upgrade through the Plugins page in your IDE and read the new README.
