### ISSUE TITLE
The lastest plugin on plugins.jetbrains.com is very old

### ISSUE THREAD

**Issue by humazed** [long1eu/flutter_i18n#71]
Please package a new release and push it to plugins.jetbrains.com
the last update is from February.

**Comment by noordawod** [comment]
@long1eu would you be able to do that? the new Gradle build options should help with that.

**Comment by cbenhagen** [comment]
@noordawod can you provide instructions how to build and install this plug-in from the git repo?

**Comment by noordawod** [comment]
git clone ...
cd flutter_i18n/
./gradlew buildPlugin -PideaVersionPrefix={prefix}

{prefix} is one of: 181, 182, 183, 191

**Comment by noordawod** [comment]
Latest plugins are now on JetBrains.
