### ISSUE TITLE
Curly bracket notation should be used by the "Extract the string resource" functionality.

### ISSUE THREAD

**Issue by ghost** [long1eu/flutter_i18n#88]
Regarding the notes: https://github.com/long1eu/flutter_i18n#notes

It would be helpful if `ExtractStringResourceDart.kt` could use this when extracting strings. Why not always use the `${variable}` notation?

**Comment by noordawod** [comment]
@long1eu what do you think? I don't like enforcing this...

**Comment by ghost** [comment]
Maybe it could be configurable then? In some languages the space between words does not seem to make sense. If this was the default translaters would not have to know that they should modify the syntax in this case.

**Comment by long1eu** [comment]
I got your point, but I don't see why we should always use the bracket notation. That is an exception from the rule, not the rule.
