### ISSUE TITLE
In the Usage Readme, delegates are missing?

### ISSUE THREAD

**Issue by holyspidoo** [long1eu/flutter_i18n#9]
I was unable to get my app to run until I changed this:
`localizationsDelegates: [S.delegate],`

to this:
`localizationsDelegates: [S.delegate,GlobalMaterialLocalizations.delegate,GlobalWidgetsLocalizations.delegate],`

Otherwise I get null errors like 
`The getter 'openAppDrawerTooltip' was called on null.`

Is this okay? And if so, maybe the usage readme should be updated? (Amazing plugin btw)

**Comment by long1eu** [comment]
Good point. I will.

**Comment by long1eu** [comment]
done, thanks
