### ISSUE TITLE
Splash screen duration 

### ISSUE THREAD

**Issue by duduf15** [long1eu/flutter_i18n#95]
I was using  https://pub.dev/packages/flutter_i18n  fir translations in my app, due to a black screen after splash screen I had tried this plugin. It’s working well but my splash screen display duration went from 2 seconds to 6 seconds. Why is it so long? I tried with and empty project and it’s the same time

**Comment by noordawod** [comment]
@duduf15 

This doesn't sound like something related to flutter_i18n but something else that you changed or added to your project. Check the git history/diff and try to find out why.

**Comment by duduf15** [comment]
Thank you I will check
