### ISSUE TITLE
Generate i18n from command line

### ISSUE THREAD

**Issue by CalvinKern** [long1eu/flutter_i18n#96]
First off, thanks for building this fantastic plugin!

While it works wonderfully the way it was designed, it would be _even better_ if you could also have the `i18n.dart` file generated/built from the command line. My team uses a translation service to get strings in our current Android app translated. These new translations are stored in an s3 bucket where we have an automated task to commit them into our project. Since the plugin requires an open instance of Android Studio, we will no longer be able to fully automate this step on our bitrise workflow.

Is there any current way to get the `i18n.dart` file to be generated from a command line so we can fully automate our translation step?

**Comment by noordawod** [comment]
@long1eu didn't you add command-line support as well using build_runner?

**Comment by KlausJokisuo** [comment]
This would be a nice feature.

Edit: There is already a generator. https://github.com/long1eu/flutter_i18n/tree/master/flutter_l10n

**Comment by CalvinKern** [comment]
Nice find! I'll need to try that out. Thanks!
